### ISSUE TITLE
fields_for support

### ISSUE THREAD

**Issue by alexeyk13** [bootstrap-ruby/bootstrap_form#100]
Hello Stephan!

Thanks for great gem. The only problem is it's not supporting fields_for. 

I'm not using any gem for nested forms - need to pass some extra params, do some stuff, etc. The easiest solution is to use fields_for instead of form_for.

can you, please, make bootstrap_fields_for wrapper?

**Comment by blakeloverain** [comment]
fields_for as a standalone function behaves differently when used as an instance method inside a FormBuilder. ie fields_for vs form.fields_for . Sometimes I want to prefix fields with a different model entirely, not any  relation to the parent form. For example:

<%= bootstrap_form_for @album do |album_form| %>
<%= fields_for :image do |image_form| %>
    <%= image_form.file_field(:file) %>
<% end %>
<% end %>

yields: 

<input type='file' name='image[file]'/>

versus album_form.fields_for version:

<input type='file' name='album[image][file]'/>

There ought to be a bootstrap_fields_for, but I'm not sure how that would be implemented - I tried passing :builder BootstrapForm::FieldBuilder, to no avail.

**Comment by mattbrictson** [comment]
@blakeloverain Could you open a new issue with your comment explaining the need for a standalone `fields_for`? I'd rather start a new issue than reopen this one. Thanks for your help!
