### ISSUE TITLE
collection_check_boxes with checked:

### ISSUE THREAD

**Issue by tkhduracell** [bootstrap-ruby/bootstrap_form#110]
I can't get the collection_check_boxes to work with checked: - attribute. If I use bootstrap_form_tag what do the checked: accept? 
- `checked: [1,2,3,4]`
- `checked: ["1","2","3","4"]`
- `checked: MyActiveModel.all`

E.g.
`<%= f.collection_check_boxes "[search][post_type][]", PostType.all, :id, :name, checked: ["1"], hide_label: true %>`

**Comment by kroteDev** [comment]
`<%= f.collection_check_boxes :disciplina_ids, Disciplina.all, :id, :nome, checked: JSON.parse(@professore.disciplina_ids) %> `
In My Controller i store the values using 
`:disciplina_ids => []`
This way i can store an array of values and retrieve then on edit
