### ISSUE TITLE
Failing get_help_text_by_i18n_key on Anonymous classes

### ISSUE THREAD

**Issue by pvmeerbe** [bootstrap-ruby/bootstrap_form#282]
Hi,

I'm experiencing the same issue as found by #217 when using rails-bootstrap-forms with trailblazer/reform  (http://trailblazer.to/)

This framework uses anonymous classes for its form objects and fails on
https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/form_builder.rb#L428

as anonymous classes return nil on the .name function

can you comment on why the provided patch in #217 was not merged?

**Comment by mattbrictson** [comment]
Thanks for bringing this to my attention!

I don't know why the owner of the original PR ending up closing it. Would you like to champion this issue and open a new PR? If your PR provides a good test and doesn't break backwards compatibility, I will be happy to merge it in.

**Comment by pvmeerbe** [comment]
see pull request https://github.com/bootstrap-ruby/rails-bootstrap-forms/pull/285

**Comment by lcreid** [comment]
It looks like this is fixed by #285. If I misunderstood, feel free to re-open it.
