### ISSUE TITLE
Ruby warning: ambiguous first argument

### ISSUE THREAD

**Issue by mattbrictson** [bootstrap-ruby/bootstrap_form#311]
Running `rake test` with the latest version of Rake produces this warning:

```
bootstrap_form/helpers/bootstrap.rb:82: warning: ambiguous first argument; put parentheses or a space even after `/' operator
```

**Comment by lcreid** [comment]
I'm not seeing this in any of the versions (5.0.6, 5.1.4, and 5.2.0.beta2) that I've been testing with. @mattbrictson If you're not seeing it anymore, maybe we can close this?

**Comment by mattbrictson** [comment]
Yep, seems to be fixed 👍
