### ISSUE TITLE
Additional form group attributes don't work for date_select and time_select

### ISSUE THREAD

**Issue by katahreza** [bootstrap-ruby/bootstrap_form#347]
Hi!
`f.date_select :my_date, wrapper: { class: 'additional-class' } `
or
`f.date_select :my_date, wrapper_class: 'additional-class'`

generate

`<div class="form-group">` without 'additional-class'

Wherein for text_field additional attributes are generated normally

**Comment by pachacamac** [comment]
for others struggling .. this actually works:

`f.date_select :my_date, {start_year: Date.current.year, end_year: Date.current.year + 1}, {class: 'form-control'}`

**Comment by lcreid** [comment]
Thanks for the suggestion, @pachacamac . I'm sure lots of people struggle with this, so your contribution is welcome. 

Could you please show us the generated HTML so that we can be sure what you mean by the "created child-elements"? Thanks in advance.

**Comment by mattbrictson** [comment]
I'll consider this fixed by #473 and b41295e.
