### ISSUE TITLE
Rename repository to bootstrap_form?

### ISSUE THREAD

**Issue by mattbrictson** [bootstrap-ruby/bootstrap_form#373]
I always thought it was confusing that this GitHub repository is named `rails-bootstrap-forms`, whereas the gem is `bootstrap_form`.

Does anyone know the story behind this? The CSS uses the non-gem name as well: https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/796bd76b87a7b73825e728cd3df9fdc46af227c3/app/assets/stylesheets/rails_bootstrap_forms.css

Would it make sense to rename the repository to `bootstrap_form` for consistency?

**Comment by GBH** [comment]
Renaming it to `bootstrap_form` would only make sense. Should create repo with old name that redirects to the new one though.

**Comment by donv** [comment]
Renaming to `bootstrap_form` makes perfect sense.

**Comment by mattbrictson** [comment]
I've renamed the repo to `bootstrap_form`, such that the canonical GitHub URL is now https://github.com/bootstrap-ruby/bootstrap_form. If anyone runs into problems as a result of this rename, please let me know!

**Comment by lcreid** [comment]
I couldn't fetch until I changed my upstream by using git config --edit` and fixing the upstream configuration. Note that there are three changes to the URL:
* No more "rails-"
* "-" becomes "_"
* No more "s" at the end

**Comment by mattbrictson** [comment]
Hmm, that's unfortunate. GitHub claims that git remotes should automatically redirect from the old to the new URL: https://github.com/blog/1508-repository-redirects-are-here

And for me, it does seem to work. My git config references the old URL and `git fetch` and `git pull` still work OK.

```
$ git remote get-url origin
git@github.com:bootstrap-ruby/rails-bootstrap-forms.git
$ git pull
Updating fffd6cb..bb794b5
Fast-forward
 test/bootstrap_form_test.rb | 19 +++++++++++++++----
 1 file changed, 15 insertions(+), 4 deletions(-)
```

My apologies. I didn't think this would have any affect on contributors!

**Comment by mattbrictson** [comment]
Is anyone else having problems? I can open a support ticket with GitHub if this turns out to be a widespread issue.

**Comment by lcreid** [comment]
I had the problem almost immediately after you made the change. I assume DNS is involved here, and even a 5 or 10 minute DNS TTL might have had me using an old record rather than the redirect.
