### ISSUE TITLE
[v4] Rendering of checkboxes and radios changed

### ISSUE THREAD

**Issue by GBH** [bootstrap-ruby/bootstrap_form#395]
Right now I see:

```html
<div class="form-check">
  <label class="form-check-label" for="user_misc_1">
    <input class="form-check-input" type="checkbox" value="1" name="user[misc][]" id="user_misc_1" />
    Foo
  </label>
</div>

<div class="radio">
  <label for="user_misc_1">
    <input type="radio" value="1" name="user[misc]" id="user_misc_1" />
    Foo
  </label>
</div>
```
Where it should be:

```html
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Default checkbox
  </label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
  <label class="form-check-label" for="exampleRadios1">
    Default radio
  </label>
</div>
```

See: https://getbootstrap.com/docs/4.0/components/forms/#default-stacked

**Comment by mattbrictson** [comment]
Good find. Definitely a bug we need to fix for 4.0.0.

**Comment by lcreid** [comment]
@jeffblake mentioned this in a comment on #361. It's good to track this in its own issue.

**Comment by lcreid** [comment]
Should custom radio buttons be rendered the same as before:
```
      <div class="custom-control custom-radio">
        <input class="custom-control-input" id="user_misc_1" name="user[misc]" type="radio" value="1" />
        <label class="custom-control-label" for="user_misc_1">This is a radio button</label>
      </div>
```
Should custom radio buttons be rendered the same as before:
```
      <div class="custom-control custom-checkbox">
        <input name="user[terms]" type="hidden" value="0" />
        <input class="custom-control-input" id="user_terms" name="user[terms]" type="checkbox" value="1" />
        <label class="custom-control-label" for="user_terms">I agree to the terms</label>
      </div>
```

**Comment by lcreid** [comment]
This is what needs to be done for this issue (moved here from PR #407):

- [x] correcting the classes on the radio button elements (https://github.com/bootstrap-ruby/bootstrap_form/pull/407#issuecomment-361032165)
- [x] inline radios and checkboxes
- [x] custom controls -- Looks like this was already done. Let me know if you see any discrepancies between our output and the Bootstrap 4 documentation
- [ ] update the README where the examples of generated markup are out-of-date
- [ ] the "no label" case

Bonus marks for investigating how accessibility is facilitated for radio buttons and check boxes (e.g. perhaps including an intelligent default for `aria-label`).

**Comment by lcreid** [comment]
@mattbrictson I think everything I sent you over the weekend has a fundamental misunderstanding on my part. I wrapped the radios and check boxes in a `<div class="form-group"...`, when that should have been left to an explicit call to `form_group`. I will look at this shortly and hopefully have a less panicked response later today.

Sorry!

**Comment by lcreid** [comment]
@mattbrictson would you entertain a PR to slightly clean up the check box and radio button code? I hesitate to even call it a refactoring. I just think we could make some variable names consistent and put lines in the same order in a few methods. It would help see where the similarities are, and would thus make finishing check boxes, radio buttons, and their collection equivalents.
