### ISSUE TITLE
`collection_radio_buttons` and `collection_check_boxes` Need to be Reviewed for Bootstrap 4

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#416]
The changes to `radio_with_bootstrap` and `check_box_with_bootstrap` may require some options that aren't currently being passed from their corresponding collection methods. This issue may require the following actions (feel free to suggest others):

- [ ] Write test cases to confirm the desired functionality. This may require a clearer definition of the functionality of the helpers
- [x] Review how the helpers functioned in the last released version. It's possible that the options weren't being passed before. If so, any changes would have to be reviewed in case they're breaking changes
- [ ] Implement the desired functionality

**Comment by lcreid** [comment]
I've checked the legacy gem, and the code generated for `collection_check_boxes` seems to work (I cut and paste output from the legacy `bootstrap_form`: https://www.bootply.com/FytFDSQ8WS). Does it work because `form-inline` class on the `form` applies over the whole form?

**Comment by lcreid** [comment]
With output from `collection_radio_buttons` from the Bootstrap 4 code in master, it looks like we have to pass the `inline` option down to `radio`, so we get `form-check-inline` applied to the labels. Otherwise, the label is squished into the radio button. (You can see by removing and adding `form-check-inline` to the `label`'s class [here](https://www.bootply.com/6jWOlrKC3M).) I couldn't figure out how to get decent spacing for the `label` under the `form-group`.

I don't consider myself a Bootstrap expert. That's why I use `bootstrap_form` -- so I don't have to know what I'm doing. :-) So if anyone can suggest a good way forward, I'd really appreciate it.

**Comment by lcreid** [comment]
It looks like the answer to spacing of the first `label` of the `collection_radio_buttons` or `collection_check_boxes`: Simply wrap the first `label` and hidden `input` like any of the other pairs output by the helper. https://www.bootply.com/4Z5xbHQfeU.

Does that sound like the right thing to do?

**Comment by mattbrictson** [comment]
Sorry, I haven't had time to dig into this one.

Is the problem just for inline forms, or does the non-inline markup need to be changed as well? I'm trying to get a sense of whether we can release 4.0.0.alpha1 before resolving this issue.

**Comment by lcreid** [comment]
I feel like I've pulled on a loose piece of wool in a sweater, and it's all unravelling. I fear there are other markup changes we need to make to this gem fully compatible with Bootstrap 4. The question is how to identify them. One thought would be to release an alpha version with clear warnings that there are rough edges in some areas, and that we need people to use the alpha version and help define what the markup should be. Another option would be for us to try to recruit some community members to define what the Bootstrap 4 markup should be for some different variations of options to the helpers. At any rate, I will continue to plug away at trying to identify what this really should do.

**Comment by lcreid** [comment]
https://github.com/bootstrap-ruby/bootstrap_form/issues/412#issuecomment-362403856 and https://github.com/bootstrap-ruby/bootstrap_form/issues/412#issuecomment-362406527 apply to this issue as much as they apply to #412. If the Bootplies referenced in those comments look good, I'd suggest that we (I?) implement them before we release the alpha.

**Comment by lcreid** [comment]
I believe PR #433 addresses this issue. I suggest we close this, and if we find any other problems with `collection_radio_buttons` or `collection_check_boxes`, we open a new issue.
