### ISSUE TITLE
`invalid-feedback` should be inside `input-group`

### ISSUE THREAD

**Issue by colinbm** [bootstrap-ruby/bootstrap_form#417]
The style that triggers display of the error is (amongst others) `.form-control.is-invalid ~ .invalid-feedback`.

Currently the `.invalid-feedback` div is outside the `.input-group` and as `.is-valid` is set on the input itself, it's never displayed.

This has been addressed in https://github.com/twbs/bootstrap/pull/25020

> Added support for form validation feedback in input groups. .input-group now has flex-wrap: wrap; on by default, allowing you to place validation feedback within the .input-group and style it based on the input's overall state. This isn't applicable to file inputs though.

This means the `.invalid-feedback` should be located as the last item inside `.input-group`.

I will take a look at this myself and see if I can fix, but it's probably an easy fix for someone who knows the code better. Thanks if you get there first!

**Comment by lcreid** [comment]
A big thank you for taking the time to report this. And thanks for offering to take a look at a fix. I encourage you to have a go at submitting a PR. We really like to get first-time contributions. Post comments here if you need help and I'll try to give a hand. I'm pretty new to the code myself. Take a look at the [CONTRIBUTING](https://github.com/bootstrap-ruby/bootstrap_form/blob/master/CONTRIBUTING.md) document if you haven't already.

As you know if you've read #361, we're in the middle of trying to prepare an official release of `bootstrap_form` for Bootstrap 4, so we're all pretty busy. And this is a completely community-supported gem. So your help would be really appreciated, but don't feel pressured if you can't.

**Comment by lcreid** [comment]
Fixing this would move me towards being able to finish #410 and #418, so I'll take a stab at a PR. Let me know if that's a bad thing.

**Comment by colinbm** [comment]
Go for it. I have got as far as writing a test for it, but my prospective fix seems... very wrong. (Regex replace after the html is generated)

**Comment by lcreid** [comment]
I'd love to get your test case, if you can push it to your fork and send me a link. Or even just cut and paste it into a comment here.

**Comment by colinbm** [comment]
Will do tomorrow. Away from computer at the moment.

**Comment by lcreid** [comment]
@colinbm take a look at PR #422, if you have a chance. Let me know what you think. I'll add your test case when I get it.

**Comment by colinbm** [comment]
@lcreid Looks good. You appear to have written the exact same test already! :)

https://github.com/colinbm/bootstrap_form/commit/f035bf2a33095450327dd7966c16c8c160786710
