### ISSUE TITLE
form_group renders incorrect offset classes for Bootstrap v4

### ISSUE THREAD

**Issue by raveman** [bootstrap-ruby/bootstrap_form#425]
Bootstrap 4 has different offset classes:
`offset-sm-2` instead of `col-sm-offset-2`

[layout documentation](https://getbootstrap.com/docs/4.0/layout/grid/#offsetting-columns)

**Comment by lcreid** [comment]
Thanks for reporting this. We really appreciate your feedback (and patience while we get this version ready for release). Definitely something we need to fix for the alpha release of the Bootstrap 4 version.
