### ISSUE TITLE
`:append` and `:prepend` not applied to collection selects.

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#428]
If the user provides `:append` and `:prepend` options to `select`, the text/HTML will be appended or prepended to the control. If the user provides those options to `collection_select` or `grouped_collection_select`, they have no effect. I don't see why this should be inconsistent.

I'm not sure whether this is a bug or a feature request.

At ae08c5b1 (Feb 15, 2014), specifically https://github.com/bootstrap-ruby/bootstrap_form/commit/ae08c5b1fb224612b0eb3d2f7433f1dca8bf1790#diff-d858d9de5eda99f11a7840b6c015c89eR8 and https://github.com/bootstrap-ruby/bootstrap_form/commit/ae08c5b1fb224612b0eb3d2f7433f1dca8bf1790#diff-d858d9de5eda99f11a7840b6c015c89eR40, the handling of `select` and `collection_select` were moved out of the "generic" definition of the `bootstrap_form` helpers. In doing so, it looks like they both lost `:append` and `:prepend`.

It looks like it was fixed for `select` with PR #327 (Apr 24, 2017), but not for the other select methods.

**Comment by lcreid** [comment]
https://github.com/bootstrap-ruby/bootstrap_form/pull/327#issuecomment-364352655 says there was no reason why only `select` got `:prepend` and `:append`.

**Comment by donv** [comment]
Right, I added what I needed at the time.

**Comment by lcreid** [comment]
@donv no worries. I agree that it's best to do what you need and no more. I just wanted to make sure your comment was visible in this issue, too. Thanks very much for your support!

**Comment by lcreid** [comment]
The Bootstrap [documentation for input groups](https://getbootstrap.com/docs/4.0/components/input-group/) implies that input groups can wrap `input` tags, custom selects, and custom file input, but not the browser default versions of selects and file inputs.
