### ISSUE TITLE
Add global config options

### ISSUE THREAD

**Issue by potenza** [bootstrap-ruby/bootstrap_form#43]
It would be nice if we add support for global config options to avoid the necessity of defining them all the time.

**Comment by GBH** [comment]
:-1: It's trivial to create a view helper that wraps `bootstrap_form_for`. For example:

```ruby
def horizontal_bootstrap_form_for(object, options = {}, &block)
  options[:layout] = :horizontal
  bootstrap_form_for(object, options, &block)
end
```
Gives you more flexibility compared to global settings too.

**Comment by donv** [comment]
Closing this issue as obsolete and not concrete enough.  Open a new issue if you need a specific global config.
