### ISSUE TITLE
Overriding `layout: :inline` at field level.

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#432]
The [README](https://github.com/bootstrap-ruby/bootstrap_form#custom-field-layout) says that specifying a layout at the field level overrides the layout specified a the form level. The example shows a `:default` layout at the field level overriding a `:horizontal` form layout.

The documented example works, but it may be difficult to make the field-level `layout:` override a form-level `layout: :inline`. The form-level `class="form-inline"` appears to cause layout changes throughout the form that it's beyond my CSS abilities to figure out how to override.

I suggest we simply update the documentation to clarify that form-level `layout: :inline` can't be overridden, but I'm open to other suggestions.

**Comment by mattbrictson** [comment]
> I suggest we simply update the documentation to clarify that form-level layout: :inline can't be overridden

Agreed 👍
