### ISSUE TITLE
inline option on date_select

### ISSUE THREAD

**Issue by lancecarlson** [bootstrap-ruby/bootstrap_form#460]
The default output of the date_select fields when using horizontal layout on the form does not look good. The fields stack on top of each other. Perhaps there should be a way to specify inline: true on it so you can override this behavior?

**Comment by lcreid** [comment]
Thanks for reporting this. We really appreciate your feedback.

Can you please confirm that [this Bootply](https://www.bootply.com/xIjouEAIwR) is what you're seeing?  I see what you mean, that it's not really what someone would expect on a horizontal form. 

Is [this Bootply](https://www.bootply.com/UVog5qkacr) more like what you'd like to see? It certainly seems a lot better to me this way.

**Comment by lancecarlson** [comment]
@lcreid Yes! I think that's exactly what someone would be expecting. I haven't verified the actual look, but from an html perspective, this looks right. Thank you!

**Comment by lcreid** [comment]
@lancecarlson are you interested in submitting a PR for this? We always appreciate contributions from the community. If not, no worries. I have some time this week and can probably put something together. Please just let me know what you like to do.

**Comment by lancecarlson** [comment]
@lcreid please review! ^

**Comment by lcreid** [comment]
This issue should probably include `time_select` and `datetime_select`, shouldn't it?

**Comment by lcreid** [comment]
This was closed by PR #461.
