### ISSUE TITLE
No offset in form_group classes without label when multiple cols values are specified

### ISSUE THREAD

**Issue by 0x0badc0de** [bootstrap-ruby/bootstrap_form#478]
Example:
```
<%= bootstrap_form_with(model: foo, layout: :horizontal, label_col: "col-sm-4 col-md-2", control_col: "col-sm-8 col-md-10") do |form| %>
  <%= form.form_group do %>
    <%= form.submit %>
  <% end %>
<% end %>
```

Resulting `div` for `form_group` will have `class="col-sm-8 col-md-10 col-sm-4 col-md-2"`. While expected one is `class="col-sm-8 col-md-10 offset-sm-4 offset-md-2"`
Probably pattern in [offset_col](https://github.com/bootstrap-ruby/bootstrap_form/blob/v4.0.0.alpha1/lib/bootstrap_form/form_builder.rb#L342-L344) should be updated to something like `/\bcol-(\w+)-(\d)\b/` and `sub` replaced with `gsub`.

**Comment by lcreid** [comment]
Great catch! Thanks for the feedback. Would you like to submit a PR to fix this? We're happy to take contributions from the community. If you don't want to submit a PR, just tell us and we'll fix it.
