### ISSUE TITLE
Required: true is no longer being passed to the html views

### ISSUE THREAD

**Issue by gafemoyano** [bootstrap-ruby/bootstrap_form#496]
Hi, I've been using bootstrap_form for the past 6 months on my rails project, running the master branch to get bootstrap 4 support. I've recently noted that the required: true option is no longer being passed to the generated html, so client side validation for required fields is not being picked up by bootstrap.

Eg:

` <%= f.text_field :name, required: true %>
`
Outputs:
`<input value="" class="form-control" type="text" name="profile[name]" id="profile_name">`

Expected:
`<input value="" class="form-control" type="text" name="profile[name]" id="profile_name" required="required">`

**Comment by lcreid** [comment]
Thanks very much for reporting this problem. PR #488 probably introduced this behaviour. I haven't had a chance to think through all the ramifications of this, but my immediate reaction is to say that we should not break existing code. Please be patient while we look at this, or feel free to submit a PR if you want.

Again, thanks for using `bootstrap_form` and reporting this issue!
