### ISSUE TITLE
Rails 6 support

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#503]
Ensure that `bootstrap_form` will work with Rails 6.

- [x] Check if the TravisCI pipeline is already testing Rails edge.
- [x] Add the next version of Rails to the TravisCI pipeline if it's not already there.
- [x] Fix any errors found.
- [ ] Bonus marks: Enhance the build pipeline so we're always testing the next version, allowing certain errors, but preventing people from adding features to the current version that won't work in the next version.

If you want to work on this, assign the issue to yourself. You can do one or more items on the checklist -- no need to do them all. If you're not actively working on this issue, please unassign the issue so others can work on it.

If you find a specific issue where `bootstrap_form` is incompatible with Rails 6, please create an issue for it, and refer to this issue. Thanks in advance!

**Comment by nevware** [comment]
it appears that Rails 6 includes the Trix editor as part of Action Text, and this doesn't work with bootstrap_form. May require update to documentation, but following the [instructions](https://edgeguides.rubyonrails.org/action_text_overview.html#installation) causes an unselectable box on the form.

**Comment by lcreid** [comment]
@nevware Thanks for reporting this! Would you mind creating a separate issue for it? It's easy to manage the work if we have a separate issue for each broken bit that we find. Thanks again for taking the time to give feedback.

**Comment by nevware** [comment]
Done: https://github.com/bootstrap-ruby/bootstrap_form/issues/508

**Comment by lcreid** [comment]
Version 4.3.0 has been deemed the official Rails 6.0.0 version. There is at least one reported issue with the rich text area support still (#540).
