### ISSUE TITLE
form-text not mentioned in the docs

### ISSUE THREAD

**Issue by krtschmr** [bootstrap-ruby/bootstrap_form#512]

**Comment by lcreid** [comment]
Could you please provide a description of the issue you want us to address? Thanks.

**Comment by krtschmr** [comment]
` help: "you can buy up to 100$" ` 

this will generate the neccessary element with class `form-text` . however, the docs only talk about the I18N for `help` and it never says that you can put `help: ` into the form

**Comment by lcreid** [comment]
The README does mention and give an example of adding help text, but I admit it does get kind of lost in the coverage of internationalization. Do you have a suggestion for what would make it stand out more?

**Comment by krtschmr** [comment]
@lcreid can you show me where? i still can't see it

**Comment by lcreid** [comment]
It's here: https://github.com/bootstrap-ruby/bootstrap_form#help-text, but admittedly it's one line and then it goes on to talk about internationalization.

I'm playing with some ideas that I hope will make the documentation a little easier to use. With luck I'll have something to look at this weekend, if you're interested.

**Comment by krtschmr** [comment]
i think the biggest isse is the fact that bootstrap class is called 
`form-text` while we call it `help`. i actually searched for "form-text" 
and couldnt find it in the docs. so that's what i was making the issue 
for

**Comment by lcreid** [comment]
Doh! I get it now. It's true the docs often show what will be generated. I was wondering if that was useful. Your comment indicates that it is.

I'm working on an evolution of the README page. I'll take your comments into account in re-write.

**Comment by lcreid** [comment]
Fixed by #521, I believe. Reopen this issue if you disagree.
