### ISSUE TITLE
static_control prevents update using form_with 

### ISSUE THREAD

**Issue by jpaulomotta** [bootstrap-ruby/bootstrap_form#523]
**My version of the gem: **  `4.1.0`

Using `<%= form.static_control label: 'Client', value: workout.user.name %>` was preventing the form to update the record. 

I was getting `ActionController::RoutingError (No route matches [POST] "/admin/workouts/8"):` error.

Setting name to nil solved the issue.

`<%= form.static_control label: 'Cliente', value: workout.user.name, name: nil %>`

Do you think this should be in the documentation?

## Static Controls

> Current docs

(...)
You can also create a static control that isn't based on a model attribute:

```erb
<%= f.static_control label: "Custom Static Control" value: "Content Here" %>
```

**Comment by lcreid** [comment]
Thanks very much for reporting this issue! We really appreciate people taking the time to let us know when there are problems.

You're right that this should be in the documentation, but it also seems to me that it would be better if we can fix the code so this doesn't happen. 

Would it be possible for you to post the generated HTML from when it was throwing the RoutingError? At least the `<form>` tag and the tags related to the static control? I'd like to see if I can see a reason why it causes that error. Also if you could add the `bootstrap_form_for` or `bootstrap_form_with` from your code, that would be helpful.

In the meantime, if I get a chance I'll try to reproduce the error based on what you've given me.

Thanks again for the report!

**Comment by jpaulomotta** [comment]
Here it goes:

This is my form tag:

```erb
<%= bootstrap_form_with(model: [:admin, workout]) do |form| %>
  <%= form.alert_message "Favor corrigir os erros abaixo." %>
  <%= form.hidden_field :workout_type %>
  <%# ===== Line where the issue happens %>
  <%= form.static_control label: 'Cliente', value: workout.user.full_name %>

  <%= form.text_field :name, help: 'Para uso interno. O cliente não vê o nome.'%>

  <label class="label-control">Data de início</label>
  <%= form.date_select :start_date, layout: :inline, hide_label: true %>
    
  <label class="label-control">Data de término</label>
  <%= form.date_select :end_date, layout: :inline, hide_label: true %>
  
  <%= form.text_area :trainer_notes, rows: 5, help: 'As observações do treinador são visíveis para o cliente.' %>
    <div class="form-group">
      <%= form.check_box :equipament_number_visible, custom: :switch %>
    </div>

  <%= form.primary 'Salvar e Continuar' %>
<% end %>

```

Form tag:
```html
<form role="form" action="/admin/workouts/13" accept-charset="UTF-8" data-remote="true" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input type="hidden" name="_method" value="patch" />
  <input type="hidden" name="authenticity_token" value="HVO823fgZpZjeNpyReXiq2FqBCu8FizSykHOZpl5hDM5wF70M0CmCpRlyKYQzEG2djUoHwLMArJAWUvYxoAD0g==" />
```

Static tag that errors:
```html
<div class="form-group"><label for="workout_">Cliente</label><input value="John Doe" readonly="readonly" class="form-control-plaintext" type="text" name="workout[]" id="workout_" /></div>
```

Chrome Stack trace on form submission:
![Screen Shot 2019-03-11 at 11 32 54 AM](https://user-images.githubusercontent.com/1813007/54131640-82abfe80-43f1-11e9-8c7c-658209ecc926.png)


== After setting `name: nil``
```erb
<%= form.static_control label: 'Cliente', value: workout.user.full_name, name: nil %>
```

Form tag:
```html
<form role="form" action="/admin/workouts/13" accept-charset="UTF-8" data-remote="true" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input type="hidden" name="_method" value="patch" />
  <input type="hidden" name="authenticity_token" value="yCyzqwxn7fxLkLoRYRpuu4R2cbgHiE+Ty7A62bcR+Nbsv1GESMctYLyNqMU0M82mkyldjLlSYfNBqL9n6Oh/Nw==" />
```

Static tag
```html
<div class="form-group"><label for="workout_">Cliente</label><input value="Luiz Inácio Lula da Silva" readonly="readonly" class="form-control-plaintext" type="text" id="workout_" /></div>
```

I hope this helps.

**Comment by lcreid** [comment]
Thanks for this. I reproduced your problem on a simpler test case, and figured out what's going on, I think. I'm not yet sure if there's a fix in the code, but I will change the documentation.

I believe the problem is related to not passing a field name to `static_control`. When one passes the value, the field name isn't actually used, but a `name` attribute is still generated for the static control that has nothing where it normally would have a field name. This causes grief for the Rails UJS handler somehow (I didn't trace all the JavaScript to figure out). 

As long as one passes a `value` option, one can pass anything for the field name, and UJS seems to be happy. When you passed `name: nil`, you also caused the `name` attribute of the static control to be something that was acceptable to UJS.

If it's not too much bother, could you try changing your line:
```
<%= form.static_control label: 'Cliente', value: workout.user.full_name, name: nil %>
```
to
```
<%= form.static_control :full_name, label: 'Cliente', value: workout.user.full_name %>
```
and tell me if that also works?

Thanks in advance, and again, thanks for reporting this issue.

**Comment by jpaulomotta** [comment]
Icreid,

Your line of code worked. I got a notice on the rails longs about unpermitted parameters but it's ok.

I think your solution is more elegant than setting `name: nil`

Thanks a lot for your help.

**Comment by jpaulomotta** [comment]
Fantastic @lcreid.

Thanks.
