### ISSUE TITLE
`invalid-feedback` element isn't rendering

### ISSUE THREAD

**Issue by geraddavis** [bootstrap-ruby/bootstrap_form#552]
Currently running
`Rails 5` 
`Ruby 2.6`
`Bootstrap 4+`
`Bootstrap_form 4.3`

I can't figure out how to invoke the `invalid-feedback` element. The ReadME file makes it seem like this element should rendered by default but it isn't. I've tried forcing this by setting the form to `inline_errors: true` and I'm not seeing a change. 

Is this something that only comes in after a trip to the server? I'm hoping to use it for client-side validation. I can get around this with the `wrapper: false` setting on the input element and adding my own markup, but doing so feels like I'm omitting a chunk of functionality that is very useful otherwise. 

Here's my the code snippet of my form (HAML):
```
= bootstrap_form_for(@user),
      html: { class: 'needs-validation', novalidate: true },
      validate: :user_validators) do |f|
      .row
        .col.mb-4
          = f.hidden_field :url_hash, value: nil
          = f.email_field :email, required: true, autofocus: true, autocomplete: :off,
            placeholder: t('###')
          = f.password_field :password, required: true, autocomplete: :off,
            placeholder: "###"
    
      .row
        .col.text-center
          = f.submit t('v2.log_in.form.button'), class: 'btn btn-primary',
            title: t('v2.log_in.form.button')
```

Here's the generated HTML
```HTML
<form class="needs-validation" novalidate="novalidate" role="form" id="" action="" accept-charset="UTF-8" method="post">
<input name="utf8" type="hidden" value="✓">
<input type="hidden">
<div class="row">
 <div class="col mb-4">
  <input type="hidden" name="" id="" value="">
 <div class="form-group">
  <label class="required" for="user_email">Email</label>
  <input required="required" autofocus="autofocus" autocomplete="off" placeholder="" class="form-control" type="email" value="" name="" id="user_email">
 </div>
 <div class="form-group">
  <label class="required" for="user_password">Password</label>
  <input required="required" autocomplete="off" placeholder="password" class="form-control" type="password" name="" id="user_password">
 </div>
</div>
</div>
<div class="row">
<div class="col text-center">
<input type="submit" name="commit" value="Log In" class="btn btn-primary btn-rounded mb-3" title="Log In" data-disable-with="Log In">
</div>
</div>
</form>
```

**Comment by brandondrew** [comment]
The claim in the README that this was handled automatically was probably the main reason I chose bootstrap_form over Simple Form.  This bug was reported months ago.  Is there any reason it is being ignored?  This is really really huge.

**Comment by lcreid** [comment]
Thanks for the feedback, and my apologies for the slow response. 

To clarify, `bootstrap_form` is very much built around Rails back-end validation. If you're taking advantage of validation in the browser, `bootstrap_form` may not give you any help. However, it shouldn't prevent you from doing anything on the front-end, either. 

I will look into the README and try to clarify our claims.

If you see an opportunity to make `bootstrap_form` integrate better with browser validation, we'd love to see a pull request, or even more discussion about it. I'm not strong on front-end development, and my current job doesn't use `bootstrap_form` so any help you can give me would be greatly appreciated.

**Comment by lcreid** [comment]
I think this is related to #504  and #502.

**Comment by lcreid** [comment]
I updated the README to state that this gem doesn't help you with client-side validation.

I found this page helpful in understanding the issues and seeing some possible solutions: https://www.jorgemanrubia.com/2019/02/16/form-validations-with-html5-and-modern-rails/.

Thanks for the feedback. If you have any ideas about how this gem could integrate better with client-side validation, please open another issue or a pull request.
