### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#553]
This is a high-level issue to capture the tasks needed for version 5 of `bootstrap_form`/`bootstrap_form` for Bootstrap 5.

Some links to relevant resources:

* https://v5.getbootstrap.com/docs/5.0/migration/#forms
* https://blog.templatetoaster.com/news/bootstrap-5/

To contribute, create an issue or pull request (PR). If you're making a PR, be sure to do it against the `bootstrap-5` branch.

Remember to add to `UPGRADE-5.0.md` if your PR changes the behaviour of the gem, and particularly if the rendered HTML and/or CSS change in a way that might cause the page to render differently.

**Comment by taylorthurlow** [comment]
The Bootstrap 5 alpha [is out today](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/)!

**Comment by o-t-w** [comment]
The Bootstrap 5 stable release was back in May. Is there any progress on this? Bootstrap 5 looks a lot better and I am desperate to upgrade.

**Comment by thimo** [comment]
A 5.0 release would be quite nice, but in the meantime you can use the bootstrap-5 branch as documented here: https://github.com/bootstrap-ruby/bootstrap_form/tree/bootstrap-5#installation

**Comment by michaelbaudino** [comment]
Shouldn't this be closed, since it has been done in #611 and released as [5.0.0](https://github.com/bootstrap-ruby/bootstrap_form/releases/tag/v5.0.0)?

**Comment by lcreid** [comment]
Thanks, @michaelbaudino . My bad. We appreciate the feedback.
