### ISSUE TITLE
checkboxes in horizontal forms render weird

### ISSUE THREAD

**Issue by rileytg** [bootstrap-ruby/bootstrap_form#556]
Checkboxes end up over on the right. Any other info i can provide?

<img width="1194" alt="Symphony_Next_Beta-8" src="https://user-images.githubusercontent.com/692817/73015001-0aafb280-3dd0-11ea-8489-3864d682c16d.png">

```haml
= bootstrap_form_with(model: @foo, inline_errors: false, local: true, layout: :horizontal, label_col: "col-sm-3 text-sm-right", control_col: "col-sm-9") do |f|
  .card
    %h5.card-header= title
    .card-body
      = f.text_field :name
      - unless @mssql_server.code.present?
        = f.text_field :code
      = f.text_field :host
      = f.text_field :port
      = f.text_field :version
      = f.form_group do
        = f.check_box :linux, custom: :switch

    .card-footer
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to 'Cancel', link_to_cancel, class: 'btn btn-secondary'
```

**Comment by donv** [comment]
Hi @rileytg !

Are you still interrested in this?  Is so, I will take a look.

Maybe the field should follow the same pattern as the other fields and have a label to the left and the switch left aligned in the rioght column?

**Comment by donv** [comment]
I think this is now fixed.  Please reopen if there is more to do.
