### ISSUE TITLE
Implement Configuration Options

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#561]
One of the good features of `bootstrap_form` is that it doesn't require a complicated configuration process before you can use it.

Also, configuration options can greatly increase the development challenge, as you may need test cases for each variation of a configuration option.

On the other hand, there are a lot of good ideas for the future of `bootstrap_form` that require breaking changes. It would be relatively easy to introduce new features if they could be controlled by an configuration option, so that people who needed the legacy behaviour could retain it easily.

This issue is asking for proposed PRs for a configuration mechanism for `bootstrap_form`. The mechanism is likely a file in `config/initializers`, but we're open to other ideas if they have significant benefits.

If you choose to work on this ticket, please write up a brief description of what you plan to do, and assign the issue to yourself (with the "Asignees" like above and to the right).

**Comment by sharshenov** [comment]
Unfortunately, I don't have sufficient right to assign myself, but here is a draft PR #562  for the requested feature, which also closes #560
