### ISSUE TITLE
Purgecss does not know about styles used by bootstrap_form

### ISSUE THREAD

**Issue by maltesa** [bootstrap-ruby/bootstrap_form#564]
I am using purgecss to decrease the size of my css bundle and to purge all unused css. I am also using `boostrap_form` to build my forms. Now purgecss purges to much of the boostrap styles if I create a form like the following, since there are no classes etc. used. 

My current solution is to use the styles used by `bootstrap_form` in a dummy `html.erb` file to avoid purging of these classes (i just copied the rendered html of a form there). A nicer solution would be to use purgecss whitelisting (https://purgecss.com/whitelisting.html). Or maybe it is possible to make purgecss aware of the classes used by `bootrap_form`.

I think a note on purgecss with a list of classes to whitelist would be great :)

```haml
= bootstrap_form_with(model: user, local: true) do |form|
  = form.text_field :username
  = form.email_field :email
  = form.password_field :password
  = form.password_field :password_confirmation
  .actions
    = form.submit
```

I am using this `postcss.config.js` to purge unused css from my bundle:
```javascript
// postcss.config.js

let environment = {
  plugins: [
    require("postcss-import"),
    require("postcss-flexbugs-fixes"),
    require("postcss-preset-env")({
      autoprefixer: {
        flexbox: "no-2009",
      },
      stage: 3,
    }),
  ],
};

// Only run PurgeCSS in production (you can also add staging here)
// if (process.env.RAILS_ENV === "production") {
environment.plugins.push(
  require("@fullhuman/postcss-purgecss")({
    content: [
      "./app/**/*.html.erb",
      "./app/**/*.html.haml",
      "./app/helpers/**/*.rb",
      "./app/javascript/**/*.js",
      "./app/javascript/**/*.jsx",
      "./app/javascript/**/*.ts",
      "./app/javascript/**/*.tsx",
    ],
  })
);
// }

module.exports = environment;
```

**Comment by lcreid** [comment]
Thanks very much for taking the time to report this. It's an interesting issue. I'd be happy to accept a documentation pull request, giving some notes on how to combine purgecss and bootstrap_form. My immediate feeling is that it's a bit beyond the scope of this gem to support the range of asset build and deploy tools out there.

One alternative would be for you to publish a small gem that adds the purgecss whitelist, and otherwise just depends on bootstrap_form.

**Comment by maltesa** [comment]
Thanks for your reply.
Yes, it is probably a bit out of scope and putting it into a separate gem seems a good idea. For now the solution with the dummy file works quite well for me, if I come up with a better solution I will mention it here and/or create a pull request to update the documentation.
