### ISSUE TITLE
`form_group` Implementation

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#568]
With Bootstrap 5, the concept of the form group basically goes away. The internal implementation of the form group (`form_group` method) dates back to at least Bootstrap 3 (if not earlier). While it made sense then, it may be overkill now. 

With a major version change, now is the time to consider refactoring the method and removing the public. This issue is meant for discussion, but can turn into a PR if there's easy consensus on what to do.

**Comment by donv** [comment]
I think this was resolved for the 5.0.0. release.

**Comment by lcreid** [comment]
There's unnecessary code, I believe, but at this point we're so far down the Bootstrap 5 road that I think it's appropriate to close this issue.
