### ISSUE TITLE
Simplify rendering of file_field for Bootstrap 5 alpha 3

### ISSUE THREAD

**Issue by thimo** [bootstrap-ruby/bootstrap_form#572]
Bootstrap 5 alpha 3 can now render a very nice looking file selector without needing additional classes or extra markup.

Current markup for `f.file_field :image`:

```
<div class="mb-3">
  <label class="form-label" for="workout_video_image">Image</label>
  <div class="form-file">
    <input class="form-file-input" type="file" name="workout_video[image]" id="workout_video_image">
    <label class="form-label form-file-label" for="workout_video_image">Choose file</label>
  </div>
</div>
```

Can be simplified to:

```
<div class="mb-3">
  <label class="form-label" for="workout_template_image">Image</label>
  <input class="form-control" type="file" name="workout_video[image]" id="workout_video_image">
</div>
```

More information can be found here: https://v5.getbootstrap.com/docs/5.0/forms/form-control/#file-input

I'd like to try to make this change myself, but if someone else is in a position to pick this up feel free to do so.

**Comment by lcreid** [comment]
Nice catch! We'd love to see a PR for this. If you have time to work on it, just assign the issue to yourself (so no one else starts working on it), and have a go. Thanks very much for your contribution.

(And no worries if you don't find time to do this. We'll get it done eventually.)

**Comment by thimo** [comment]
@lcreid I'd like to (finally) start working on this and assign this issue to myself. But I can't seem to find the option to do so. Any help on how I can do that? Ir maybe you can assign it to me? Same for the other issue I created: https://github.com/bootstrap-ruby/bootstrap_form/issues/573.

**Comment by lcreid** [comment]
Hmmm. Maybe you're not allowed to assign yourself. The history of this gem is long, and none of us currently have full permissions on the repo, so maybe we're stuck with people not being able to assign themselves. Thanks for pointing that out.
