### ISSUE TITLE
Change the name of the main branch to `main`

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#575]
Change the name of the main branch to `main`.

We're changing the name because, for a significant proportion of English-speakers, the word "master" means "owner of slaves". By using "master", we could be signalling to some people that they're not welcome to participate in this project. By changing the name to "main", we avoid needlessly discouraging people from participating in this project.

Another reason is that since GitHub will be making "main" the default, in a few years most people will instinctively use "main" rather than "master". 

To rename the default branch in your local copy of this repository:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

If you have any problems, search the GitHub docs and the Internet for help.

GitHub links: https://github.com/github/renaming

**Comment by donv** [comment]
What is the purpose of this change?

**Comment by lcreid** [comment]
I updated the description to give some motivation. It looks like the tooling is mostly there, but it's still worthwhile to wait, if possible, until there aren't too many PRs in progress. So we'll definitely wait until we get CI working again and some of the Bootstrap 5 backlog (if any) done.

**Comment by lcreid** [comment]
It appears that being a committer doesn't give permission to change the name of the default branch.

**Comment by donv** [comment]
I think we should drop this issue.

**Comment by lcreid** [comment]
I'm interested in understanding why we would _not_want to do this?

**Comment by lcreid** [comment]
Completed.
