### ISSUE TITLE
Help Wanted: Maintainer Needed

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#577]
Unfortunately, I don't use this gem at work anymore, and I have found I simply don't have the time to keep up with it. A bit more help from people who are willing to be committers would ensure that this gem continues to provide really useful services in the future. 

We need people who can deal with changes to the code, as well as people who can help maintain our build and CI pipeline (e.g. travisci.org is going away soon. Will that affect us?).

Let me know if you're interested by commenting on this issue.

**Comment by donv** [comment]
I am still using this gem at work and am happy to contribute.

**Comment by donv** [comment]
I'll start work on setting up GitHub Actions.

**Comment by lcreid** [comment]
> I am still using this gem at work and am happy to contribute.

Thanks so much, @donv !

**Comment by thimo** [comment]
Let me know if you can use an extra set of hands. I'm using this gem in several projects and quite like it.

**Comment by thimo** [comment]
With Bootstrap 5 officially released we might want to prepare an official bootstrap_form 5 release. Is there anything I can do to help with this?

**Comment by lcreid** [comment]
Thanks, Thimo. I'm sure there's something to do. Something that's been nagging me is that Bootstrap 5 no longer has a `form-group` mark-up. Part of me thinks we should remove the `form_group` method. But quite a bit of the gem's functionality was built around the assumption that most things had to be wrapped in a `form-group`. What are your thoughts on the subject?

**Comment by lcreid** [comment]
@thimo Are you still interested in moving this gem forward? I'm just not going to have the time to do anything more than more release the Bootstrap 5 version as-is, and I'd like to work with you on that if you're interested.

**Comment by o-t-w** [comment]
Seeing as you are talking about releasing v5 "as-is", what is preventing you from the release, seeing as "as is" makes it sound like there is no more to do?

**Comment by donv** [comment]
Version 5.0.0. has been released, so we will move forward that way.  I would like to allow overriding the wrapper_class, but that comes in a separate PR.
