### ISSUE TITLE
Get CI working

### ISSUE THREAD

**Issue by donv** [bootstrap-ruby/bootstrap_form#578]
I'll start setting up GitHub Actions, but travis is not green, and when I run tests locally, 171 of 260 tests fail.

@lcreid  Is the release branch master or bootstrap-5 ?

Any comments are welcome.

**Comment by donv** [comment]
I have 4 of 9 tests green 😄

**Comment by donv** [comment]
5 of 10 jobs green including Lint (rubocop)

**Comment by donv** [comment]
OK, basic setup is done.  We have failures for Rails 6.1 and Rails edge and for Ruby 3.0.0, but that is not new, it is present in travis as well.

Anybody know why the generated HTML should be different for Ruby 3.0.0?

**Comment by donv** [comment]
Fixed the Ruby 3.0 keyword args problem.  6 of 10 jobs are green.

**Comment by lcreid** [comment]
It looks like you're making great progress. Thanks!

I'm curious: Does the fix for Ruby 3 keyword arguments imply a breaking change for existing applications that might migrate to Ruby 3?

**Comment by lcreid** [comment]
Also, keep in mind that we only _commit_ to supporting `bootstrap_form` for supported versions of Ruby and Rails. We can choose to test older versions, but if getting the tests to run on an unsupported version of Ruby or Rails is causing you grief, feel free not to run the tests on the offending old version.

**Comment by thimo** [comment]
CI seems to be fine now. Can we close this, or are there any open issues?

**Comment by lcreid** [comment]
What I'm worried about is that TravisCI seems to be moving away from unlimited free use: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. So even if things are green now, we may need to move to something else. But perhaps we need another issue for that, and we can close this one? But I think you're right. It makes more sense to close this one and create a new issue for the Travis issue.
