### ISSUE TITLE
bootstrap_form not support 'min'-Attribute after validation fail

### ISSUE THREAD

**Issue by QuAcK3RjAcK** [bootstrap-ruby/bootstrap_form#589]
bootstrap_form is not supporting HTML attribute after validation failed:

`= f.number_field :food_waste_main, label: "XXX", step: "0.01", min: @food_waste_min`

is generating correctly following HTML:

```
<div class="form-group">
  <label class="required" for="feedback_food_waste_main">XXX</label>
  <input step="0.01" min="0.97" class="form-control" type="number" name="feedback[food_waste_main]" id="feedback_food_waste_main">
</div>
```

But after i submit form and validation failed it's not supporting attribute "min" anymore:

```
<div class="form-group">
  <label class="required" for="feedback_food_waste_main">XXX</label>
  <input step="0.01" class="form-control is-invalid" type="number" value="" name="feedback[food_waste_main]" id="feedback_food_waste_main">
  <div class="invalid-feedback">bitte angeben</div>
</div>
```

Using *bootstrap_form (4.5.0)*

**Comment by lcreid** [comment]
Thanks for taking the time to report this problem. I'm sorry it's not working for you. We're a completely volunteer-supported gem, so if you feel up to creating a pull request (PR), please do so. If you plan to create a PR, please comment here so we don't duplicate effort.

Otherwise, we'll take a look at the problem in the near future.

Could you also please confirm which version of `bootstrap_form` you're using, the line for `bootstrap_form` from your `Gemfile.lock` should tell you.

Thanks again for bringing this to our attention!

**Comment by QuAcK3RjAcK** [comment]
@lcreid Thx for response. I mentioned version at Bottom: "Using bootstrap_form (4.5.0)"

Unfortunately i don't have time to look on my own, sry for that :( It's not a big banger, i fixed it by using validations for the value, but i wanted to report the issue.

Thx for the Gem and your efforts!

**Comment by lcreid** [comment]
My bad. Sorry. I was rushing a response and didn't re-read the original report. 

@QuAcK3RjAcK Would you mind posting the entire controller action here, or one that reproduces the problem? I have an idea about what the problem might be. Seeing the controller action would help me know sooner if I'm on the right path.

**Comment by QuAcK3RjAcK** [comment]
No problem, here is my controller action. I simply use `valid?`and render the action if it fails.

```
  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.valid?
      flash[:success] = "Bewertung erfolgreich gespeichert. Danke!"
      @feedback.save
      redirect_to welcome_index_path
    else
      render customer_feedbacks_new_path
    end
  end
```

**Comment by lcreid** [comment]
@QuAcK3RjAcK Is it possible you forgot to set an instance variable `@food_waste_min` in the `create` method/action? If I make a `create` method in a controller and render the new template on error, without `@food_waste_min` defined in the method, I get the behaviour that you reported.

Perhaps add: `@food_waste_min = 5` after the `else` and before the `render` in you `create` method. (I'm sure 5 isn't the right value, but you know what I mean. And if not, feel free to ask.)

**Comment by QuAcK3RjAcK** [comment]
@lcreid wow big thx for this hint! That is the solution :)

Never think about that, but its clear. It renders the view without that value so its set to `nil`. And without value it doesn't generate the attribute.
