### ISSUE TITLE
Consider Moving Off of Travis CI

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#595]
TravisCI seems to be moving away from unlimited free use: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. We should evaluate our options and move to CI that's going to be supported and free for the long term.

**Comment by olleolleolle** [comment]
@lcreid Hello, I just posted #600, and I am guessing the current answer in the repo is "use GitHub Actions".

**Comment by olleolleolle** [comment]
@lcreid Hi! This seems completed!

**Comment by lcreid** [comment]
Thanks, @olleolleolle !
