### ISSUE TITLE
select does not allow setting id attribute

### ISSUE THREAD

**Issue by brandondrew** [bootstrap-ruby/bootstrap_form#597]
I can control the `id` of any of my fields except for the select fields:

```
= f.select        :job_title, job_title_selection, selected: job.preferred_title, required: true, id: "#{id_prefix}-job_title"
```

generates

```
<div class="form-group"><label class="required" for="reappointment_job_title">Job title</label><select class="form-control" name="reappointment[job_title]" id="reappointment_job_title"><option value="ACT INSTR-GRAD STDNT-GSHIP">Acting Instructor I-III - Partial Fee Remission</option>
<option value="blah">blah</option>
<option value="blah">blah</option>
</select>
</div>
```

**Comment by brandondrew** [comment]
for some reason GitHub was not allowing me to edit this after it was errantly submitted by a keystroke meant to move the cursor

**Comment by lcreid** [comment]
> for some reason GitHub was not allowing me to edit this after it was errantly submitted by a keystroke meant to move the cursor

Odd.

**Comment by lcreid** [comment]
Thanks for getting in touch with us. Did you resolve your issue?
