### ISSUE TITLE
Where do I start hacking to allow this to work with honeypot-captcha?

### ISSUE THREAD

**Issue by walterdavis** [bootstrap-ruby/bootstrap_form#601]
I'm looking here: https://github.com/curtis/honeypot-captcha/blob/master/lib/honeypot-captcha/form_tag_helper.rb at how honeypot-captcha resets the form_tag_html method. I have applied this gem to my application, and it does not appear to have any effect on a `bootstrap_form_with` form. Any suggestions how I can get these two on speaking terms?

**Comment by lcreid** [comment]
@walterdavis did you figure out how to get these two to talk to each other?

**Comment by walterdavis** [comment]
Yup. It was as simple as ensuring that honeypot-captcha was earlier in the Gemfile than bootstrap_form.

**Comment by lcreid** [comment]
Thanks!
