### ISSUE TITLE
Investigate Rails 7 Tests/Config Needing `sassc`

### ISSUE THREAD

**Issue by lcreid** [bootstrap-ruby/bootstrap_form#614]
We had to add `sassc` to the `test` group in the `Gemfile`, in order to get tests to run in Rails 7. We're not sure why. It would be nice to understand what the change was that caused this.

**Comment by donv** [comment]
Sprockets is no longer part of Rails 7 by default, so any config for `assets` will give error.  Removing both `sassc-rails` and `demo/config/initializers/assets.rb` solves the test error.
