### ISSUE TITLE
inline validation for fields_for

### ISSUE THREAD

**Issue by no1-knows** [bootstrap-ruby/bootstrap_form#656]
Hello!  In this code, title and content fields show inline errors properly but staple_food and main_dish doesn't.
Is there a mistake?
```
<%= bootstrap_form_with(model: @recipe_form, url: @recipe_form.persisted? ? recipe_path : recipes_path) do |form| %>

  <%= form.text_field :title %>
  <%= form.text_area :content %>

  <%= form.fields_for :genres do |g| %>
    <%= g.text_field :staple_food %>
    <%= g.text_field :main_dish %>
  <% end %>

  <%= form.submit %>
```

**Comment by lcreid** [comment]
Hi. Thanks for bringing this to our attention. Would you mind posting the HTML that this generates, and/or a screen shot of the rendered page? Thanks in advance.

**Comment by donv** [comment]
Hi @no1-knows !

Do you have any more information for us?
