### ISSUE TITLE
Set required and aria on input when input is required

### ISSUE THREAD

**Issue by CharlieWinkwaves** [bootstrap-ruby/bootstrap_form#663]
I fixed this before in https://github.com/bootstrap-ruby/bootstrap_form/pull/605 and https://github.com/bootstrap-ruby/bootstrap_form/pull/606 for both bootstrap 4 and 5 but somehow it got overwritten by a merge??

So here are the changes again

**Comment by donv** [comment]
@CharlieWinkwaves Thank you! Where are the changes?
