### ISSUE TITLE
I can't Disable select field

### ISSUE THREAD

**Issue by Ahmunna** [bootstrap-ruby/bootstrap_form#670]
I have this form
```
# file.html.haml
= bootstrap_form_tag(url: my_url) do |f|
  = f.select :nationality, nationalities, { selected: 'FR', disabled: true }
```
I can't disable the select field for some reason, do you have any idea why ?

**Comment by shivam091** [comment]
@Ahmunna You have follwing wrong syntax of select. Please check the syntax and make sure options and html_options you passed are at right place.

Thank you

**Comment by donv** [comment]
The correct syntax is

```slim
  = f.select :nationality, nationalities, {selected: 'FR'}, disabled: true
```
