### ISSUE TITLE
Range control has wrong class

### ISSUE THREAD

**Issue by joeroe** [bootstrap-ruby/bootstrap_form#677]
`<%= f.range_field :excellence %>` generates:

```html
<div class="mb-3">
  <label class="form-label" for="user_excellence">Excellence</label>
  <input class="form-control" id="user_excellence" name="user[excellence]" type="range">
</div>
```

According to the [Bootstrap 5 docs](https://getbootstrap.com/docs/5.3/forms/range/), the input should have the class `form-range`, not `form-control`.

**Comment by tylercal** [comment]
This appears to still be broken if you add other attributes to the range. E.,g.

```ruby
f.range_field :test,  min: 0, max: 80
```

generates
```html
<div class="mb-3">
  <label class="form-label" for="u_test">Test</label>
  <input min="0" max="80" class="form-control" type="range" name="u[test]" id="u_test">
</div>
```

**Comment by eliang** [comment]
Issue still occuring on version 5.0.0.alpha1

**Comment by UweKubosch** [comment]
What about the latest release?

**Comment by tylercal** [comment]
Just tested this again with `5.4.0` still broken in the exact same way.

**Comment by tylercal** [comment]
confirmed as working in `main` version of gem. Will look forward to the next release!
