### ISSUE TITLE
Release version 5.2.0

### ISSUE THREAD

**Issue by donv** [bootstrap-ruby/bootstrap_form#680]
Hi all!

I think it is time for a 5.2.0 release.

Major points:

* Support current rubies: 3.0, 3.1, and 3.2 (https://www.ruby-lang.org/en/downloads/branches/)
* Support current Rails versions: 6.0, 6.1, 7.0 (https://guides.rubyonrails.org/maintenance_policy.html)
* Support current Bootstrap versions: 5.0, 5.1, and 5.2, and aspire to support Bootstrap 5.3.

## What's Changed
* More portable `docker-compose.yml` and better documentation by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/647
* Document exposing ports for docker-compose by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/648
* CVE fix breaks serialization of symbols -- fix test by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/649
* This allows running tests on the root of the project freshly checked out by @donv in https://github.com/bootstrap-ruby/bootstrap_form/pull/651
* Change `concat` to `<<` since the buffer no longer supports the former by @donv in https://github.com/bootstrap-ruby/bootstrap_form/pull/652
* Eliminate Warnings from `net-http` by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/650
* Automatically pick up presence validators for default belongs_to association by @donv in https://github.com/bootstrap-ruby/bootstrap_form/pull/654
* Add Puma and Debuggers to common.gemfile by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/657
* Lint on oldest Rails version by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/658
* Fix the bogus Rubocop Autocorrect by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/659
* Don't use `concat` when not necessary by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/660
* Set required and aria-required on the input when the input is required by @CharlieWinkwaves in https://github.com/bootstrap-ruby/bootstrap_form/pull/664
* Use the minitest test runner by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/666
* Update gemspec by @siegy22 in https://github.com/bootstrap-ruby/bootstrap_form/pull/667
* Test extra arguments by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/668
* CI Updates by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/669
* Test wrapper_class and wrapper: { class: specified by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/671
* Remove tests for versions before Rails 5.2 by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/672
* 674 html tests by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/676
* Fix assets in the demo app by @lcreid in https://github.com/bootstrap-ruby/bootstrap_form/pull/678

## New Contributors
* @siegy22 made their first contribution in https://github.com/bootstrap-ruby/bootstrap_form/pull/667

**Comment by lcreid** [comment]
Wow. A lot of contributions. I confess I lost track of where we were at. Thanks @donv for putting this together. 

@donv if you're up for it, I _think_ I gave you permissions that might allow you to prepare the release. Feel free to give it a go, or let me know if you want me to do it.

**Comment by donv** [comment]
I'll give it a go 😄

**Comment by donv** [comment]
I worked through `RELEASING.md` and it generated #681 .I'll merge that and do the RubyGems release.

**Comment by donv** [comment]
Looks like I need access in rubygems.org:

    You do not have permission to push to this gem. Ask an owner to add you with: gem owner bootstrap_form --add uwe@kubosch.no

**Comment by donv** [comment]
@lcreid Can you add me as owner on rubygems.org ?

**Comment by lcreid** [comment]
@donv Done. I think. I'm pretty sure I found you on rubygems.org. If you don't see an invitation soon, please let me know.

**Comment by donv** [comment]
@lcreid Thanks!  Release pushed!  Woohoo!

I improved the release process in some places.  There is more to do, but I have done enough for this release.

**Comment by lcreid** [comment]
Awesome. Thank you, @donv !
