### ISSUE TITLE
Rename the default layout to "vertical" ?

### ISSUE THREAD

**Issue by donv** [bootstrap-ruby/bootstrap_form#687]
As stated in the [Bootstrap docs](https://getbootstrap.com/docs/5.3/forms/layout/#forms):

"forms will by default stack vertically"

The current name, "default", does not actually hold any meaning.  Also, the default can be changed to "inline" or "horizontal".

I propose we change the name of the default layout to "vertical".

What do you think?

**Comment by lcreid** [comment]
I agree that `vertical` would be much more explicit and clear. I would suggest we continue to recognize `default`, but remove all mention of it from the documentation. Bonus marks for outputting a deprecation message if the user uses `default`.

**Comment by donv** [comment]
I'll start working on this now.
