### ISSUE TITLE
DEPRECATION WARNING: Calling `<<` to an ActiveModel::Errors message array in order to add an error is deprecated

### ISSUE THREAD

**Issue by dannytip** [bootstrap-ruby/bootstrap_form#689]
When using `bootstrap_form` > `v5.1.0` with rails `v6.1.7.4` i receive the following deprecation warning:

`DEPRECATION WARNING: Calling `<<` to an ActiveModel::Errors message array in order to add an error is deprecated. Please call `ActiveModel::Errors#add` instead.`

I believe its coming from this line:

https://github.com/bootstrap-ruby/bootstrap_form/blob/main/lib/bootstrap_form/components/validation.rb#L74

**Comment by lcreid** [comment]
Thanks for taking the time to help us make this gem better. This is a good find. Are you interested in submitting a pull request to fix it?

**Comment by dannytip** [comment]
@lcreid i'll try take a look when i get a moment.
