### ISSUE TITLE
Release new version (5.3.0)

### ISSUE THREAD

**Issue by donv** [bootstrap-ruby/bootstrap_form#697]
Hi!

I'd like to release a new version.  We have several useful changes I'd like to get into a stable release.

To indicate that we support Bootstrap 5.3, and that we have stopped support for Rails 6.0, I'd like to bump the version to 5.3.0.

Sounds good?

**Comment by lcreid** [comment]
Yes. Let's put out a new version. Thanks so much for staying on top of this.

**Comment by donv** [comment]
https://github.com/bootstrap-ruby/bootstrap_form/releases/tag/v5.3.0
