### ISSUE TITLE
`collection_check_boxes` does not work with Rails 6.1

### ISSUE THREAD

**Issue by av-martin** [bootstrap-ruby/bootstrap_form#717]
It appears to be missing a method called `field_name` somewhere:

![image](https://github.com/bootstrap-ruby/bootstrap_form/assets/100691050/e01384f5-24e1-43f2-94e2-ff08b7437604)

I can provide a sample project, if that would be helpful :)

**Comment by lcreid** [comment]
Thanks for bringing this to our attention. It would be very helpful is you can show us a bit of the code that's causing the issue. If there's a publicly available project that reproduces the problem, that's even better. Thanks again for taking the time to report this!

**Comment by av-martin** [comment]
Sure thing, i've made a sample project that triggers the bug here: https://github.com/av-martin/bootstrap_form_gem_sample

The line that triggers the bug is here: https://github.com/av-martin/bootstrap_form_gem_sample/blob/4a58634f189143a147abd2949bf2b85d80b01b6f/app/views/members/_form.html.erb#L15

Thanks for taking a look :)

**Comment by lcreid** [comment]
@donv It looks like you meant to address this in https://github.com/bootstrap-ruby/bootstrap_form/pull/698. If you get a chance, can you take a look at this issue? Thanks in advance.

**Comment by rocket-turtle** [comment]
We also got thie error and set `include_hidden` to `false` because there is no version with the fix.

`form.collection_check_boxes(..., include_hidden: false)`

Just in case someone stumbles across this.
