### ISSUE TITLE
Allow disabling form_group generation per field

### ISSUE THREAD

**Issue by wingrunr21** [bootstrap-ruby/bootstrap_form#89]
I had a use case today where I wanted to append asterisks after the required inputs. Best way I can think to handle use cases like this is to simply allow disabling the `form_group` generation. Users can use the existing `form_group` helper to create the markup they want.

This would also give people the ability to have two text inputs inline with each other (eg for first name, last name collection) while living within the same `form_group`

**Comment by fabn** [comment]
I'd also need this. Is there any progress?

**Comment by gradybarrett** [comment]
This is a pretty big point of annoyance when it comes to trying to render multiple inputs inline:

```html
<div class="row">
      <div class="col-md-12">
        <div class="input-group">
          <input type="text" class="form-control">
          <span class="input-group-addon">%</span>
          <span class="input-group-addon">at</span>
          <span class="input-group-addon">$</span>
          <input type="text" class="form-control">
          <span class="input-group-addon">.00</span>
        </div>
      </div>
    </div>
```

Any chance this is getting worked on?

**Comment by mattbrictson** [comment]
If someone is willing to contribute, I will consider merging a PR that adds the `form_group: false` feature, provided it comes with tests and docs. 👍

**Comment by mattbrictson** [comment]
Those who are following this issue: could you please test the branch in PR #259 to see if it is a good solution? Let me know! If it gets a positive response I'll merge it.

**Comment by aminbs** [comment]
Hey Matt that would be great

**Comment by jeffblake** [comment]
+1, as shown here: https://getbootstrap.com/docs/4.0/components/forms/#form-grid

Form grid's don't use `form-group` wrappers

**Comment by donv** [comment]
I think we have enough options to cover these use cases now.
